import { City, Activity, User, Trip, TripStop, ItineraryDay, ItineraryActivity, Expense } from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'user-demo',
    name: 'Sarah Jenkins',
    email: 'sarah.judge@globetrotter.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    bio: 'Product designer & world traveler. Always looking for hidden gem cafes and scenic routes.',
    preferredCurrency: 'INR',
    travelStyle: 'Balanced',
    role: 'user',
    savedDestinationIds: ['city-tokyo', 'city-bali', 'city-barcelona'],
  },
  {
    id: 'user-admin',
    name: 'Alex Rivera (Admin)',
    email: 'admin@globetrotter.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    bio: 'GlobeTrotter Platform Administrator & Growth Lead.',
    preferredCurrency: 'USD',
    travelStyle: 'Luxury',
    role: 'admin',
    savedDestinationIds: ['city-paris', 'city-dubai'],
  },
];

export const SEED_CITIES: City[] = [
  {
    id: 'city-paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    code: 'CDG',
    description: 'The City of Light captivates with timeless art, grand boulevards, iconic monuments, and world-class culinary mastery.',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Premium ($$$)',
    costLevel: 3,
    popularityScore: 98,
    lat: 48.8566,
    lng: 2.3522,
    timezone: 'GMT+2',
    avgDailyCostINR: 12500,
    topHighlights: ['Eiffel Tower', 'Louvre Museum', 'Montmartre', 'Seine Cruise', 'Notre-Dame'],
    weather: {
      temp: '22°C',
      condition: 'Sunny with breeze',
      bestSeason: 'Apr – Oct',
    },
  },
  {
    id: 'city-amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    code: 'AMS',
    description: 'Renowned for picturesque canals, cycling culture, historic canal houses, and vibrant contemporary art scenes.',
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Moderate ($$)',
    costLevel: 2,
    popularityScore: 92,
    lat: 52.3676,
    lng: 4.9041,
    timezone: 'GMT+2',
    avgDailyCostINR: 10500,
    topHighlights: ['Rijksmuseum', 'Canal Ring Cruise', 'Anne Frank House', 'Van Gogh Museum', 'Jordaan District'],
    weather: {
      temp: '19°C',
      condition: 'Partly Cloudy',
      bestSeason: 'May – Sep',
    },
  },
  {
    id: 'city-rome',
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    code: 'FCO',
    description: 'An open-air museum where nearly 3,000 years of globally influential art, architecture, and culture meet mouthwatering cuisine.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Moderate ($$)',
    costLevel: 2,
    popularityScore: 96,
    lat: 41.9028,
    lng: 12.4964,
    timezone: 'GMT+2',
    avgDailyCostINR: 9800,
    topHighlights: ['Colosseum', 'Vatican Museums', 'Trevi Fountain', 'Pantheon', 'Trastevere'],
    weather: {
      temp: '26°C',
      condition: 'Warm & Clear',
      bestSeason: 'Apr – Jun, Sep – Oct',
    },
  },
  {
    id: 'city-tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    code: 'HND',
    description: 'A dazzling juxtaposition of ultramodern neon skyscrapers and historic Shinto shrines with unmatched hospitality.',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Premium ($$$)',
    costLevel: 3,
    popularityScore: 99,
    lat: 35.6762,
    lng: 139.6503,
    timezone: 'GMT+9',
    avgDailyCostINR: 11000,
    topHighlights: ['Shibuya Crossing', 'Senso-ji Temple', 'TeamLab Planets', 'Shinjuku Gyoen', 'Akihabara'],
    weather: {
      temp: '20°C',
      condition: 'Pleasant',
      bestSeason: 'Mar – May, Oct – Nov',
    },
  },
  {
    id: 'city-bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    code: 'DPS',
    description: 'The Island of the Gods offers lush terraced rice paddies, serene spiritual temples, surf-ready beaches, and wellness sanctuaries.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Budget ($)',
    costLevel: 1,
    popularityScore: 94,
    lat: -8.3405,
    lng: 115.092,
    timezone: 'GMT+8',
    avgDailyCostINR: 4800,
    topHighlights: ['Ubud Monkey Forest', 'Tanah Lot Temple', 'Tegallalang Rice Terraces', 'Seminyak Sunset', 'Mount Batur Sunrise'],
    weather: {
      temp: '29°C',
      condition: 'Tropical Sunshine',
      bestSeason: 'Apr – Oct',
    },
  },
  {
    id: 'city-london',
    name: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    code: 'LHR',
    description: 'A 21st-century metropolis with history stretching back to Roman times, iconic theatre, Royal Parks, and royal landmarks.',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Premium ($$$)',
    costLevel: 3,
    popularityScore: 95,
    lat: 51.5074,
    lng: -0.1278,
    timezone: 'GMT+1',
    avgDailyCostINR: 13500,
    topHighlights: ['Tower of London', 'British Museum', 'London Eye', 'Westminster Abbey', 'Borough Market'],
    weather: {
      temp: '18°C',
      condition: 'Mild',
      bestSeason: 'May – Sep',
    },
  },
  {
    id: 'city-barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    code: 'BCN',
    description: 'The cosmopolitan capital of Catalonia, known for stunning Gaudí architecture, sun-kissed beaches, and lively tapas culture.',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Moderate ($$)',
    costLevel: 2,
    popularityScore: 93,
    lat: 41.3851,
    lng: 2.1734,
    timezone: 'GMT+2',
    avgDailyCostINR: 8900,
    topHighlights: ['Sagrada Família', 'Park Güell', 'Gothic Quarter', 'La Boqueria Market', 'Barceloneta Beach'],
    weather: {
      temp: '24°C',
      condition: 'Sunny',
      bestSeason: 'May – Jun, Sep – Oct',
    },
  },
  {
    id: 'city-dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
    code: 'DXB',
    description: 'An ultramodern city known for luxury shopping, futuristic architecture, soaring skyscrapers, and desert adventures.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Luxury ($$$$)',
    costLevel: 4,
    popularityScore: 91,
    lat: 25.2048,
    lng: 55.2708,
    timezone: 'GMT+4',
    avgDailyCostINR: 15500,
    topHighlights: ['Burj Khalifa', 'Dubai Mall & Fountains', 'Palm Jumeirah', 'Desert Safari', 'Museum of the Future'],
    weather: {
      temp: '32°C',
      condition: 'Sunny',
      bestSeason: 'Nov – Mar',
    },
  },
  {
    id: 'city-newyork',
    name: 'New York',
    country: 'United States',
    region: 'North America',
    code: 'JFK',
    description: 'The energetic heartbeat of the world featuring Broadway, iconic skyline panoramas, Central Park, and endless neighborhood charms.',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Luxury ($$$$)',
    costLevel: 4,
    popularityScore: 97,
    lat: 40.7128,
    lng: -74.006,
    timezone: 'GMT-4',
    avgDailyCostINR: 18500,
    topHighlights: ['Central Park', 'Times Square', 'Empire State Building', 'High Line', 'Brooklyn Bridge'],
    weather: {
      temp: '23°C',
      condition: 'Clear Sky',
      bestSeason: 'Apr – Jun, Sep – Nov',
    },
  },
  {
    id: 'city-singapore',
    name: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    code: 'SIN',
    description: 'A global garden city blending futuristic botanical domes, vibrant hawker food culture, and luxury waterfronts.',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1565967511849-76a60a516170?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Premium ($$$)',
    costLevel: 3,
    popularityScore: 89,
    lat: 1.3521,
    lng: 103.8198,
    timezone: 'GMT+8',
    avgDailyCostINR: 11500,
    topHighlights: ['Gardens by the Bay', 'Marina Bay Sands', 'Sentosa Island', 'Chinatown Hawkers', 'Jewel Changi'],
    weather: {
      temp: '30°C',
      condition: 'Humid & Sunny',
      bestSeason: 'Year-round',
    },
  },
  {
    id: 'city-delhi',
    name: 'Delhi',
    country: 'India',
    region: 'Asia',
    code: 'DEL',
    description: 'India’s bustling capital where majestic Mughal fortresses, vibrant spice bazaars, and modern urban energy collide.',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1597040663342-45b6af3d91a5?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Budget ($)',
    costLevel: 1,
    popularityScore: 88,
    lat: 28.6139,
    lng: 77.209,
    timezone: 'GMT+5:30',
    avgDailyCostINR: 3500,
    topHighlights: ['Qutub Minar', 'Humayun’s Tomb', 'Red Fort', 'Chandni Chowk Street Food', 'India Gate'],
    weather: {
      temp: '25°C',
      condition: 'Sunny',
      bestSeason: 'Oct – Mar',
    },
  },
  {
    id: 'city-jaipur',
    name: 'Jaipur',
    country: 'India',
    region: 'Asia',
    code: 'JAI',
    description: 'The Pink City of Rajasthan, famous for majestic hill forts, opulent royal palaces, and vibrant artisanal textiles.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Budget ($)',
    costLevel: 1,
    popularityScore: 90,
    lat: 26.9124,
    lng: 75.7873,
    timezone: 'GMT+5:30',
    avgDailyCostINR: 3200,
    topHighlights: ['Amber Palace', 'Hawa Mahal', 'City Palace', 'Nahargarh Fort Sunset', 'Johari Bazaar'],
    weather: {
      temp: '27°C',
      condition: 'Warm & Pleasant',
      bestSeason: 'Oct – Mar',
    },
  },
  {
    id: 'city-goa',
    name: 'Goa',
    country: 'India',
    region: 'Asia',
    code: 'GOI',
    description: 'Golden sand beaches, laid-back coastal shacks, Portuguese colonial heritage, and buzzing tropical nightlife.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1587922546307-776227941871?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Budget ($)',
    costLevel: 1,
    popularityScore: 92,
    lat: 15.2993,
    lng: 74.124,
    timezone: 'GMT+5:30',
    avgDailyCostINR: 3800,
    topHighlights: ['Palolem Beach', 'Fontainhas Latin Quarter', 'Dudhsagar Waterfalls', 'Anjuna Flea Market', 'Sunset Cruise'],
    weather: {
      temp: '28°C',
      condition: 'Sea Breeze',
      bestSeason: 'Nov – Feb',
    },
  },
  {
    id: 'city-mumbai',
    name: 'Mumbai',
    country: 'India',
    region: 'Asia',
    code: 'BOM',
    description: 'The City of Dreams — a dynamic coastal powerhouse famous for Marine Drive, Bollywood glamour, and irresistible street food.',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=1600&auto=format&fit=crop&q=80',
    costIndex: 'Moderate ($$)',
    costLevel: 2,
    popularityScore: 89,
    lat: 18.922,
    lng: 72.8347,
    timezone: 'GMT+5:30',
    avgDailyCostINR: 5200,
    topHighlights: ['Gateway of India', 'Marine Drive Queen’s Necklace', 'Elephanta Caves', 'Bandra Street Art', 'Colaba Causeway'],
    weather: {
      temp: '29°C',
      condition: 'Coastal Warmth',
      bestSeason: 'Oct – Mar',
    },
  },
];

export const SEED_ACTIVITIES: Activity[] = [
  // PARIS
  {
    id: 'act-paris-1',
    cityId: 'city-paris',
    name: 'Eiffel Tower Summit Access & Champagne',
    category: 'Sightseeing',
    durationMinutes: 150,
    estimatedCostINR: 3800,
    rating: 4.9,
    reviewCount: 4820,
    description: 'Ascend to the top of Paris’s defining iron beacon for 360-degree panoramic views across the city skyline.',
    image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=600&auto=format&fit=crop&q=80',
    locationName: 'Champ de Mars, 7th Arrondissement',
    bestTimeOfDay: 'Morning',
    bookingRequired: true,
  },
  {
    id: 'act-paris-2',
    cityId: 'city-paris',
    name: 'Louvre Masterpieces & Mona Lisa Guided Tour',
    category: 'Culture & Art',
    durationMinutes: 180,
    estimatedCostINR: 4200,
    rating: 4.8,
    reviewCount: 3950,
    description: 'Skip the line and explore the world’s largest art museum with an art historian guide.',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&auto=format&fit=crop&q=80',
    locationName: 'Rue de Rivoli, 1st Arrondissement',
    bestTimeOfDay: 'Afternoon',
    bookingRequired: true,
  },
  {
    id: 'act-paris-3',
    cityId: 'city-paris',
    name: 'Montmartre Artisans & Food Tasting Walk',
    category: 'Food & Dining',
    durationMinutes: 120,
    estimatedCostINR: 3200,
    rating: 4.9,
    reviewCount: 1620,
    description: 'Taste fresh croissants, artisan cheeses, cured meats, and macarons while exploring Sacré-Cœur alleys.',
    image: 'https://images.unsplash.com/photo-1509439581779-6298f75bf6e5?w=600&auto=format&fit=crop&q=80',
    locationName: 'Montmartre, 18th Arrondissement',
    bestTimeOfDay: 'Morning',
    bookingRequired: false,
  },
  {
    id: 'act-paris-4',
    cityId: 'city-paris',
    name: 'Evening Seine River Illuminations Cruise',
    category: 'Entertainment',
    durationMinutes: 75,
    estimatedCostINR: 1800,
    rating: 4.7,
    reviewCount: 2890,
    description: 'Glide past Notre-Dame, the Louvre, and the sparkling Eiffel Tower aboard an open-air glass boat.',
    image: 'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=600&auto=format&fit=crop&q=80',
    locationName: 'Port de la Bourdonnais',
    bestTimeOfDay: 'Night',
    bookingRequired: true,
  },
  {
    id: 'act-paris-5',
    cityId: 'city-paris',
    name: 'Palace of Versailles Grand Apartments & Gardens',
    category: 'Culture & Art',
    durationMinutes: 240,
    estimatedCostINR: 4500,
    rating: 4.8,
    reviewCount: 3100,
    description: 'Walk through the dazzling Hall of Mirrors and the expansive fountain-adorned royal gardens.',
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&auto=format&fit=crop&q=80',
    locationName: 'Versailles, Île-de-France',
    bestTimeOfDay: 'Morning',
    bookingRequired: true,
  },

  // AMSTERDAM
  {
    id: 'act-ams-1',
    cityId: 'city-amsterdam',
    name: 'Canal Ring Heritage Boat Tour & Dutch Cheese Tasting',
    category: 'Sightseeing',
    durationMinutes: 90,
    estimatedCostINR: 2400,
    rating: 4.9,
    reviewCount: 2200,
    description: 'Discover UNESCO-listed waterways with live commentary, artisanal Gouda, and local craft drinks.',
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=600&auto=format&fit=crop&q=80',
    locationName: 'Prins Hendrikkade Canal Dock',
    bestTimeOfDay: 'Afternoon',
    bookingRequired: true,
  },
  {
    id: 'act-ams-2',
    cityId: 'city-amsterdam',
    name: 'Rijksmuseum & Van Gogh Museum Masterpass',
    category: 'Culture & Art',
    durationMinutes: 210,
    estimatedCostINR: 4100,
    rating: 4.9,
    reviewCount: 3400,
    description: 'Immerse yourself in Rembrandt’s Night Watch and the vibrant brushstrokes of Vincent Van Gogh.',
    image: 'https://images.unsplash.com/photo-1583200479155-2d1d4d8c7c94?w=600&auto=format&fit=crop&q=80',
    locationName: 'Museumplein',
    bestTimeOfDay: 'Morning',
    bookingRequired: true,
  },
  {
    id: 'act-ams-3',
    cityId: 'city-amsterdam',
    name: 'Jordaan District Bike & Vintage Boutique Tour',
    category: 'Adventure',
    durationMinutes: 150,
    estimatedCostINR: 2100,
    rating: 4.8,
    reviewCount: 1450,
    description: 'Pedal like a local through cobblestone alleys, 17th-century courtyards, and trendy concept shops.',
    image: 'https://images.unsplash.com/photo-1524047934117-cb5073fe61b5?w=600&auto=format&fit=crop&q=80',
    locationName: 'Jordaan Neighborhood',
    bestTimeOfDay: 'Morning',
    bookingRequired: false,
  },
  {
    id: 'act-ams-4',
    cityId: 'city-amsterdam',
    name: 'Anne Frank House Emotional Reflection Walk',
    category: 'Culture & Art',
    durationMinutes: 90,
    estimatedCostINR: 1900,
    rating: 4.9,
    reviewCount: 4200,
    description: 'Experience the secret annex where Anne Frank hid during WWII through poignant multimedia exhibits.',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&auto=format&fit=crop&q=80',
    locationName: 'Prinsengracht 263-267',
    bestTimeOfDay: 'Morning',
    bookingRequired: true,
  },

  // ROME
  {
    id: 'act-rome-1',
    cityId: 'city-rome',
    name: 'Colosseum Underground & Roman Forum VIP Access',
    category: 'Sightseeing',
    durationMinutes: 180,
    estimatedCostINR: 4800,
    rating: 4.9,
    reviewCount: 5120,
    description: 'Walk the gladiator arena floor and subterranean tunnels before exploring the ruins of the Roman Forum.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&auto=format&fit=crop&q=80',
    locationName: 'Piazza del Colosseo',
    bestTimeOfDay: 'Morning',
    bookingRequired: true,
  },
  {
    id: 'act-rome-2',
    cityId: 'city-rome',
    name: 'Vatican Museums & Sistine Chapel Early Access',
    category: 'Culture & Art',
    durationMinutes: 200,
    estimatedCostINR: 4400,
    rating: 4.9,
    reviewCount: 4600,
    description: 'Marvel at Michelangelo’s iconic Sistine Chapel ceiling and St. Peter’s Basilica before the crowds arrive.',
    image: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=600&auto=format&fit=crop&q=80',
    locationName: 'Viale Vaticano',
    bestTimeOfDay: 'Morning',
    bookingRequired: true,
  },
  {
    id: 'act-rome-3',
    cityId: 'city-rome',
    name: 'Trastevere Sunset Food Safari & Wine Pairing',
    category: 'Food & Dining',
    durationMinutes: 180,
    estimatedCostINR: 3600,
    rating: 4.9,
    reviewCount: 2180,
    description: 'Savor crispy suppli, authentic Cacio e Pepe, Roman pizza, and artisanal gelato in bohemian Trastevere.',
    image: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=600&auto=format&fit=crop&q=80',
    locationName: 'Piazza di Santa Maria in Trastevere',
    bestTimeOfDay: 'Evening',
    bookingRequired: true,
  },

  // TOKYO
  {
    id: 'act-tokyo-1',
    cityId: 'city-tokyo',
    name: 'teamLab Planets Digital Art Immersion',
    category: 'Culture & Art',
    durationMinutes: 120,
    estimatedCostINR: 3200,
    rating: 4.9,
    reviewCount: 3800,
    description: 'Walk through water and dynamic blooming infinity light rooms in this world-famous digital museum.',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600&auto=format&fit=crop&q=80',
    locationName: 'Toyosu, Koto City',
    bestTimeOfDay: 'Afternoon',
    bookingRequired: true,
  },
  {
    id: 'act-tokyo-2',
    cityId: 'city-tokyo',
    name: 'Shibuya Crossing & Izakaya Alley Night Safari',
    category: 'Nightlife',
    durationMinutes: 150,
    estimatedCostINR: 2800,
    rating: 4.8,
    reviewCount: 1900,
    description: 'Experience the world’s busiest scramble crossing and hidden yakitori bars down Nonbei Yokocho alley.',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&auto=format&fit=crop&q=80',
    locationName: 'Shibuya Center Street',
    bestTimeOfDay: 'Night',
    bookingRequired: false,
  },

  // BALI
  {
    id: 'act-bali-1',
    cityId: 'city-bali',
    name: 'Mount Batur Sunrise Trek & Hot Springs',
    category: 'Adventure',
    durationMinutes: 360,
    estimatedCostINR: 2800,
    rating: 4.9,
    reviewCount: 2900,
    description: 'Hike to the active volcanic summit for breathtaking caldera sunrise views followed by natural thermal springs.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&auto=format&fit=crop&q=80',
    locationName: 'Kintamani, Bali',
    bestTimeOfDay: 'Morning',
    bookingRequired: true,
  },
  {
    id: 'act-bali-2',
    cityId: 'city-bali',
    name: 'Ubud Sacred Monkey Forest & Rice Terrace Swing',
    category: 'Nature',
    durationMinutes: 180,
    estimatedCostINR: 1600,
    rating: 4.7,
    reviewCount: 3400,
    description: 'Wander among ancient mossy banyan temples with playful macaques and swing over Tegallalang valleys.',
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&auto=format&fit=crop&q=80',
    locationName: 'Padangtegal, Ubud',
    bestTimeOfDay: 'Morning',
    bookingRequired: false,
  },

  // JAIPUR & DELHI
  {
    id: 'act-jaipur-1',
    cityId: 'city-jaipur',
    name: 'Amber Fort Elephant Ramparts & Sheesh Mahal Tour',
    category: 'Culture & Art',
    durationMinutes: 180,
    estimatedCostINR: 1200,
    rating: 4.9,
    reviewCount: 3100,
    description: 'Explore the grand Rajput citadel overlooking Maota Lake with thousands of mirrored glass mosaics.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&auto=format&fit=crop&q=80',
    locationName: 'Amer, Jaipur',
    bestTimeOfDay: 'Morning',
    bookingRequired: false,
  },
  {
    id: 'act-jaipur-2',
    cityId: 'city-jaipur',
    name: 'Hawa Mahal Palace of Winds & Rooftop Chai',
    category: 'Sightseeing',
    durationMinutes: 90,
    estimatedCostINR: 600,
    rating: 4.8,
    reviewCount: 2400,
    description: 'Admire the 953 pink sandstone jharokhas windows and enjoy cardamom spiced tea overlooking the facade.',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&auto=format&fit=crop&q=80',
    locationName: 'Badi Choupad, Jaipur',
    bestTimeOfDay: 'Morning',
    bookingRequired: false,
  },
  {
    id: 'act-delhi-1',
    cityId: 'city-delhi',
    name: 'Old Delhi Chandni Chowk Rickshaw & Culinary Trail',
    category: 'Food & Dining',
    durationMinutes: 150,
    estimatedCostINR: 1400,
    rating: 4.8,
    reviewCount: 2200,
    description: 'Ride through historic spice markets, sampling parathas, jalebis, and sensory aromas of Khari Baoli.',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&auto=format&fit=crop&q=80',
    locationName: 'Chandni Chowk, Old Delhi',
    bestTimeOfDay: 'Evening',
    bookingRequired: true,
  },
  {
    id: 'act-goa-1',
    cityId: 'city-goa',
    name: 'Palolem Catamaran Dolphin Safari & Secluded Cove Picnic',
    category: 'Nature',
    durationMinutes: 180,
    estimatedCostINR: 1800,
    rating: 4.8,
    reviewCount: 1750,
    description: 'Sail South Goa’s tranquil turquoise waters to spot wild dolphins and relax on Butterfly Beach.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&auto=format&fit=crop&q=80',
    locationName: 'Palolem Beach, South Goa',
    bestTimeOfDay: 'Morning',
    bookingRequired: true,
  },
];

// Pre-seeded Full Trip: "European Explorer"
export const SEED_TRIPS: Trip[] = [
  {
    id: 'trip-europe-explorer',
    userId: 'user-demo',
    title: 'European Summer Explorer',
    description: 'An unforgettable 8-day multi-city journey across the historic landmarks, scenic canals, and culinary gems of Paris, Amsterdam, and Rome.',
    startDate: '2026-06-12',
    endDate: '2026-06-20',
    coverImage: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&auto=format&fit=crop&q=80',
    status: 'upcoming',
    totalBudgetINR: 180000,
    currency: 'INR',
    isPublic: true,
    shareSlug: 'europe-summer-explorer',
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-14T14:30:00Z',
  },
  {
    id: 'trip-rajasthan-royals',
    userId: 'user-demo',
    title: 'Royal Rajasthan Heritage Trail',
    description: 'Palaces, hill forts, desert sunsets, and royal culinary feasts across Delhi and Jaipur.',
    startDate: '2026-10-15',
    endDate: '2026-10-21',
    coverImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200&auto=format&fit=crop&q=80',
    status: 'planning',
    totalBudgetINR: 45000,
    currency: 'INR',
    isPublic: false,
    shareSlug: 'rajasthan-heritage-trail',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-02T11:20:00Z',
  },
  {
    id: 'trip-bali-paradise',
    userId: 'user-demo',
    title: 'Bali Island Wellness & Surf',
    description: 'Rice terraces, spiritual sanctuaries, volcanic sunrise hikes, and beach club sunsets.',
    startDate: '2025-11-05',
    endDate: '2025-11-12',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&auto=format&fit=crop&q=80',
    status: 'completed',
    totalBudgetINR: 75000,
    currency: 'INR',
    isPublic: true,
    shareSlug: 'bali-wellness-retreat',
    createdAt: '2025-10-01T08:00:00Z',
    updatedAt: '2025-11-13T16:00:00Z',
  },
];

export const SEED_TRIP_STOPS: TripStop[] = [
  // European Explorer: Paris (3 days) -> Amsterdam (2 days) -> Rome (3 days)
  {
    id: 'stop-ee-paris',
    tripId: 'trip-europe-explorer',
    cityId: 'city-paris',
    order: 1,
    arrivalDate: '2026-06-12',
    departureDate: '2026-06-15',
    nights: 3,
    transportToNext: {
      mode: 'train',
      duration: '3h 18m',
      estimatedCostINR: 6500,
      carrier: 'Eurostar High-Speed (Thalys)',
      notes: 'Depart Gare du Nord -> Amsterdam Centraal. Scenic countryside route.',
    },
  },
  {
    id: 'stop-ee-amsterdam',
    tripId: 'trip-europe-explorer',
    cityId: 'city-amsterdam',
    order: 2,
    arrivalDate: '2026-06-15',
    departureDate: '2026-06-17',
    nights: 2,
    transportToNext: {
      mode: 'flight',
      duration: '2h 10m',
      estimatedCostINR: 8200,
      carrier: 'KLM Royal Dutch Airlines',
      notes: 'Schiphol (AMS) -> Rome Fiumicino (FCO)',
    },
  },
  {
    id: 'stop-ee-rome',
    tripId: 'trip-europe-explorer',
    cityId: 'city-rome',
    order: 3,
    arrivalDate: '2026-06-17',
    departureDate: '2026-06-20',
    nights: 3,
  },

  // Rajasthan
  {
    id: 'stop-rr-delhi',
    tripId: 'trip-rajasthan-royals',
    cityId: 'city-delhi',
    order: 1,
    arrivalDate: '2026-10-15',
    departureDate: '2026-10-17',
    nights: 2,
    transportToNext: {
      mode: 'train',
      duration: '4h 15m',
      estimatedCostINR: 1200,
      carrier: 'Vande Bharat Express',
      notes: 'New Delhi (NDLS) -> Jaipur Junction (JP)',
    },
  },
  {
    id: 'stop-rr-jaipur',
    tripId: 'trip-rajasthan-royals',
    cityId: 'city-jaipur',
    order: 2,
    arrivalDate: '2026-10-17',
    departureDate: '2026-10-21',
    nights: 4,
  },
];

export const SEED_ITINERARY_DAYS: ItineraryDay[] = [
  // European Explorer Days
  {
    id: 'day-ee-1',
    tripId: 'trip-europe-explorer',
    tripStopId: 'stop-ee-paris',
    dayNumber: 1,
    date: '2026-06-12',
    title: 'Arrival & Iconic Paris Landmarks',
    notes: 'Check-in to hotel near Le Marais, pick up museum passes.',
  },
  {
    id: 'day-ee-2',
    tripId: 'trip-europe-explorer',
    tripStopId: 'stop-ee-paris',
    dayNumber: 2,
    date: '2026-06-13',
    title: 'Art, History & Bohemian Montmartre',
    notes: 'Wear comfortable walking shoes for cobblestones.',
  },
  {
    id: 'day-ee-3',
    tripId: 'trip-europe-explorer',
    tripStopId: 'stop-ee-paris',
    dayNumber: 3,
    date: '2026-06-14',
    title: 'Royal Grandeur & Seine Sunset',
    notes: 'Visit Versailles in morning, evening cruise.',
  },
  {
    id: 'day-ee-4',
    tripId: 'trip-europe-explorer',
    tripStopId: 'stop-ee-amsterdam',
    dayNumber: 4,
    date: '2026-06-15',
    title: 'Scenic Train to Amsterdam & Canal Cruise',
    notes: 'Morning Eurostar train ride. Rent city bikes in afternoon.',
  },
  {
    id: 'day-ee-5',
    tripId: 'trip-europe-explorer',
    tripStopId: 'stop-ee-amsterdam',
    dayNumber: 5,
    date: '2026-06-16',
    title: 'Dutch Masterpieces & Anne Frank Story',
    notes: 'Museumplein exploration & Jordaan dining.',
  },
  {
    id: 'day-ee-6',
    tripId: 'trip-europe-explorer',
    tripStopId: 'stop-ee-rome',
    dayNumber: 6,
    date: '2026-06-17',
    title: 'Flight to Rome & Gladiator Legacy',
    notes: 'Land at FCO, evening Roman pasta feast.',
  },
  {
    id: 'day-ee-7',
    tripId: 'trip-europe-explorer',
    tripStopId: 'stop-ee-rome',
    dayNumber: 7,
    date: '2026-06-18',
    title: 'Vatican Splendors & Sistine Chapel',
    notes: 'Strict dress code required for Vatican basilica.',
  },
  {
    id: 'day-ee-8',
    tripId: 'trip-europe-explorer',
    tripStopId: 'stop-ee-rome',
    dayNumber: 8,
    date: '2026-06-19',
    title: 'Fountains, Piazzas & Farewell Gelato',
    notes: 'Toss coin in Trevi Fountain for good luck!',
  },
];

export const SEED_ITINERARY_ACTIVITIES: ItineraryActivity[] = [
  // Day 1
  {
    id: 'ia-1',
    itineraryDayId: 'day-ee-1',
    activityId: 'act-paris-1',
    title: 'Eiffel Tower Summit Access & Champagne',
    startTime: '10:30',
    durationMinutes: 150,
    estimatedCostINR: 3800,
    category: 'Sightseeing',
    order: 1,
    locationName: 'Champ de Mars',
    image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=600&auto=format&fit=crop&q=80',
    notes: 'Skip-the-line vouchers on mobile.',
  },
  {
    id: 'ia-2',
    itineraryDayId: 'day-ee-1',
    activityId: undefined,
    title: 'Traditional French Bistro Lunch @ Café de Flore',
    startTime: '13:30',
    durationMinutes: 75,
    estimatedCostINR: 2800,
    category: 'Food & Dining',
    order: 2,
    locationName: 'Saint-Germain-des-Prés',
    notes: 'Order Croque Monsieur and Café au lait.',
  },
  {
    id: 'ia-3',
    itineraryDayId: 'day-ee-1',
    activityId: 'act-paris-4',
    title: 'Evening Seine River Illuminations Cruise',
    startTime: '20:00',
    durationMinutes: 75,
    estimatedCostINR: 1800,
    category: 'Entertainment',
    order: 3,
    locationName: 'Port de la Bourdonnais',
    image: 'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=600&auto=format&fit=crop&q=80',
  },

  // Day 2
  {
    id: 'ia-4',
    itineraryDayId: 'day-ee-2',
    activityId: 'act-paris-3',
    title: 'Montmartre Artisans & Food Tasting Walk',
    startTime: '09:30',
    durationMinutes: 120,
    estimatedCostINR: 3200,
    category: 'Food & Dining',
    order: 1,
    locationName: 'Place du Tertre',
    image: 'https://images.unsplash.com/photo-1509439581779-6298f75bf6e5?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ia-5',
    itineraryDayId: 'day-ee-2',
    activityId: 'act-paris-2',
    title: 'Louvre Masterpieces & Mona Lisa Guided Tour',
    startTime: '14:30',
    durationMinutes: 180,
    estimatedCostINR: 4200,
    category: 'Culture & Art',
    order: 2,
    locationName: 'Louvre Pyramid',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&auto=format&fit=crop&q=80',
  },

  // Day 3
  {
    id: 'ia-6',
    itineraryDayId: 'day-ee-3',
    activityId: 'act-paris-5',
    title: 'Palace of Versailles Grand Apartments & Gardens',
    startTime: '09:00',
    durationMinutes: 240,
    estimatedCostINR: 4500,
    category: 'Culture & Art',
    order: 1,
    locationName: 'Versailles',
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&auto=format&fit=crop&q=80',
  },

  // Day 4 (Amsterdam)
  {
    id: 'ia-7',
    itineraryDayId: 'day-ee-4',
    activityId: undefined,
    title: 'Scenic Eurostar Train from Paris to Amsterdam',
    startTime: '08:30',
    durationMinutes: 200,
    estimatedCostINR: 6500,
    category: 'Sightseeing',
    order: 1,
    locationName: 'Gare du Nord to Amsterdam Centraal',
  },
  {
    id: 'ia-8',
    itineraryDayId: 'day-ee-4',
    activityId: 'act-ams-1',
    title: 'Canal Ring Heritage Boat Tour & Dutch Cheese Tasting',
    startTime: '16:00',
    durationMinutes: 90,
    estimatedCostINR: 2400,
    category: 'Sightseeing',
    order: 2,
    locationName: 'Prins Hendrikkade',
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=600&auto=format&fit=crop&q=80',
  },

  // Day 5
  {
    id: 'ia-9',
    itineraryDayId: 'day-ee-5',
    activityId: 'act-ams-4',
    title: 'Anne Frank House Emotional Reflection Walk',
    startTime: '09:30',
    durationMinutes: 90,
    estimatedCostINR: 1900,
    category: 'Culture & Art',
    order: 1,
    locationName: 'Prinsengracht',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ia-10',
    itineraryDayId: 'day-ee-5',
    activityId: 'act-ams-2',
    title: 'Rijksmuseum & Van Gogh Museum Masterpass',
    startTime: '13:00',
    durationMinutes: 210,
    estimatedCostINR: 4100,
    category: 'Culture & Art',
    order: 2,
    locationName: 'Museumplein',
    image: 'https://images.unsplash.com/photo-1583200479155-2d1d4d8c7c94?w=600&auto=format&fit=crop&q=80',
  },

  // Day 6 (Rome)
  {
    id: 'ia-11',
    itineraryDayId: 'day-ee-6',
    activityId: 'act-rome-1',
    title: 'Colosseum Underground & Roman Forum VIP Access',
    startTime: '14:30',
    durationMinutes: 180,
    estimatedCostINR: 4800,
    category: 'Sightseeing',
    order: 1,
    locationName: 'Piazza del Colosseo',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ia-12',
    itineraryDayId: 'day-ee-6',
    activityId: 'act-rome-3',
    title: 'Trastevere Sunset Food Safari & Wine Pairing',
    startTime: '19:00',
    durationMinutes: 180,
    estimatedCostINR: 3600,
    category: 'Food & Dining',
    order: 2,
    locationName: 'Trastevere',
    image: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=600&auto=format&fit=crop&q=80',
  },

  // Day 7
  {
    id: 'ia-13',
    itineraryDayId: 'day-ee-7',
    activityId: 'act-rome-2',
    title: 'Vatican Museums & Sistine Chapel Early Access',
    startTime: '08:30',
    durationMinutes: 200,
    estimatedCostINR: 4400,
    category: 'Culture & Art',
    order: 1,
    locationName: 'Vatican City',
    image: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ia-14',
    itineraryDayId: 'day-ee-8',
    activityId: undefined,
    title: 'Trevi Fountain, Spanish Steps & Sunset Gelato',
    startTime: '16:00',
    durationMinutes: 120,
    estimatedCostINR: 1200,
    category: 'Sightseeing',
    order: 1,
    locationName: 'Piazza di Trevi',
  },
];

export const SEED_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    tripId: 'trip-europe-explorer',
    cityId: 'city-paris',
    title: 'Boutique Hotel Le Marais (3 Nights)',
    category: 'Accommodation',
    amountINR: 42000,
    date: '2026-06-12',
    notes: 'Charming historic quarter hotel near metro',
  },
  {
    id: 'exp-2',
    tripId: 'trip-europe-explorer',
    cityId: 'city-amsterdam',
    title: 'Canal View Hotel Amsterdam (2 Nights)',
    category: 'Accommodation',
    amountINR: 28000,
    date: '2026-06-15',
    notes: 'Jordaan boutique stay',
  },
  {
    id: 'exp-3',
    tripId: 'trip-europe-explorer',
    cityId: 'city-rome',
    title: 'Hotel Navona Roma (3 Nights)',
    category: 'Accommodation',
    amountINR: 34000,
    date: '2026-06-17',
    notes: 'Walking distance to Pantheon',
  },
  {
    id: 'exp-4',
    tripId: 'trip-europe-explorer',
    title: 'Eurostar High Speed Train (Paris -> AMS)',
    category: 'Transportation',
    amountINR: 6500,
    date: '2026-06-15',
    notes: 'First class quiet coach',
  },
  {
    id: 'exp-5',
    tripId: 'trip-europe-explorer',
    title: 'KLM Flight (AMS -> Rome FCO)',
    category: 'Transportation',
    amountINR: 8200,
    date: '2026-06-17',
    notes: 'Includes checked luggage',
  },
  {
    id: 'exp-6',
    tripId: 'trip-europe-explorer',
    title: 'Schengen Multi-Country Travel Insurance',
    category: 'Insurance & Visa',
    amountINR: 3200,
    date: '2026-05-20',
  },
];
